replacements = [
      [", kgr de azucar refinada", "azucar"],
      ["ralladura c/u", "rallado"],
      ['pancitos saborizados', "pan"],
      ['cebolla', 'cebolla'],
      ['chicas', ''],
      ['al ras de ', ''],
      [' tipo alubia, negros,', ''],
      ['sal fina', 'sal'],
      ['sal gruesa', 'sal'],
      ['chiquitas', ''],
      ['saborizada', ''],
      ['grande', ''],
      ['verduritas varias;', ''],
      ['molida/picada', 'picada'],
      ['rhum o cognac', 'rhum'],
      ['pimiento morron', 'morron'],
      ['picado', ''],
      ['chico', ''],
      ['apios', 'apio'],
      ['frutas confitadas', 'fruta confitada'],
      ['salsa de frutillas', 'salsa de frutilla'],
      ['claras', 'clara'],
      ['papas', 'papa'],
      ['tiempo', ''],
      ['c/n', ''],
      ['algo de salsa de tomate fresca.', 'salsa de tomate'],
      [' apenas tibia', ''],
      ['extracto de vainilla', 'esencia de vainilla'],
      ['150 gr ', ''],
      ['maso de ', ''],
      ['para freire', ''],
      ['para freir', ''],
      ['rollitos queso de maquina', 'queso'],
      ['sopera de ', ''],
      ['oliva oil', 'aceite de oliva'],
      ['000', ''],
      ['0000', ''],
      ['a gusto', ''],
      ['caderas de ', ''],
      ['chori puro chancho con reguianito y morron', 'chorizo'],
      ['longanizas', 'longaniza'],
      ['carne costillar de 10 kilitos', 'carne'],
      ['pasas de uvas', 'pasas de uva'],
      ['almibar:00 g azucar +00 cc agua', 'almibar'],
      ['hay en cajita en su conchilla en sup', ''],
      ['cdta. bien cargada de anis', 'anis'],
      ['manitos', 'pata de chancho'],
      ['jugo de medio ', ''],
      [',paquetes de salchichas y mostaza', 'salchicha'],
      ['salchichas', 'salchicha'],
      ['caliente', ''],
      ['medianas', ''],
      ['comunes', ''],
      [' partido', ''],
      ['opcional:', ''],
      ['1 taza de ', ''],
      ['comun', ''],
      [' "para todos los usos"', ''],
      ['condimento p/pure: ', ''],
      ['bien picadito', ''],
      ['pan frances', 'pan'],
      ['tomate perita', 'tomate'],
      ['manteca pomada', 'manteca'],
      [' entero', ''],
      [' fresco', ''],
      ['variantes : si tienes disgusto o problemas con consumir porotos y garbanzos usa arroz ya hervido o fideos', ''],
      [' de 0', ''],
      ['500 ml ', ''],
      ['de aceite', 'aceite'],
      ['leche entera', 'leche'],
      ['ingredientes', ''],
      ['dientes', ''],
      ['cdta.', ''],
      [',o mezclar', ''],
      ['aove', 'aceite de oliva'],
      ['cebollas', 'cebolla'],
      ['choclos', 'choclo'],
      ['moradas', 'morada'],
      ['te de polvo de hornear', 'polvo de hornear'],
      ['quesos: queso crema, rocquefort o queso azul', 'queso'],
      ['original', ''],
      ['pancito', 'pan'],
      ['calentado en parrilla', ''],
      ['cocidos', ''],
      ['para el bizcochuelo', ''],
      ['cebollitas', 'cebolla'],
      ['aceitunas verdes', 'aceituna verde'],
      ['maduros', ''],
      ['maduro', ''],
      ['tomates', 'tomate'],
      ['o la carne que mas te guste', ''],
      ['cortado en 4', ''],
      ['cubeteado', ''],
      ['un chorrito de agua tibia', 'agua'],
      [', en mi recetario hay una receta con harina integral', ''],
      ['mexicanas', ''],
      [':', ''],
      ['salsita', 'salsa'],
      ['tortillas', 'tortilla'],
      ['varitas de surimi', 'kanikama'],
      ['surimi', 'kanikama'],
      ['pelados', ''],
      ['pelado', ''],
      ['abundante', ''],
      ['aprox 1 litro', ''],
      ['cant. necesaria', ''],
      ['. harina', ''],
      ['aceitunas', 'aceituna'],
      ['tibia', ''],
      ['tibio', ''],
      ['huevo xl', 'huevo'],
      [' celestes', ''],
      [' de colores', ''],
      [' , y ralladura de un limon', ''],
      ['reposero', 'repostero'],
      ['aproximadamente', ''],
      ['aprox', ''],
      [' sin carozos cotadas', ''],
      [' sin carozos', ''],
      ['huevos', 'huevo'],
      ['+  - ', ''],
      ['"bizcochuelo riquisimo"', 'bizcochuelo'],
      ['/  g de ', ''],
      ['a  cc agua', 'agua'],
      ['a  cebolla s', 'cebolla'],
      [' neutro', ''],
      ['descarozadas', ''],
      ['descarozada', ''],
      ['   litro', ''],
      [' la cantidad que quieras pero no muchas porque son saladas', ''],
      [' muy picante', ''],
      ['aderezos', 'aderezo'],
      ['tapas', 'tapa'],
      ['hojaldradas', ''],
      ['hojaldrada', ''],
      ['usamos unas buenas', ''],
      [' y un poco mas  con sal', ''],
      [' fria', ''],
      [' frio', ''],
      ['trapo de cocina', ''],
      ['zapallo anco  s', 'zapallo anco'],
      ['zapallitos', 'zapallito'],
      [' cortado en bastones', ''],
      [' cortada en bastones', ''],
      [' blanqueada', ''],
      ['zanahorias', 'zanahoria'],
      ['y medio de ', ''],
      ['y media de', ''],
      ['y tooodo lo que se te ocurra y te guste para combinar las pizzas', ''],
      [' a eleccion', ''],
      [' de  gr  cortada en finas rodajas', ''],
      ['hojas de ', ''],
      ['un punado generoso de ', ''],
      ['empannadas', 'empanadas'],
      ['caseras', ''],
      ['y como opcional cacao dulce en polvo', 'cacao'],
      ['peritas', 'perita'],
      ['medianos', ''],
      ['mediano', ''],
      [' cortado en', ''],
      ['secos', 'seco'],
      ['vino blanco dulce', 'vino blanco'],
      ['ralladas', ''],
      ['rallados', ''],
      ['rallada', ''],
      ['rallado', ''],
      ['taza de ', ''],
      ['empanadas', 'empanada'],
      ['rotiseras', 'rotisera'],
      ['sarten', ''],
      ['tapa para', 'tapa de'],
      ['tapa de taco', 'tortilla'],
      ['tapa de masa para empanada', 'tapa de empanada'],
      [' s cortadas al medio', ''],
      ['variantes  si tienes disgusto', ''],
      ['ver recetario de tacos mexicanos. https//cookpad.com/ar/recetas', ''],
      ['torta bizcochuelo de vainilla', 'bizcochuelo'],
      ['spaghetti a italianos. cuadrato me.-', 'spaghetti'],
      ['salamina picada grueso de tandil', 'salame'],
      [' opcional', ''],
      ['redondo', ''],
      ['rodajas de', ''],
      ['rocquefort', 'roquefort'],
      [' condimentado con un poco de sal', ''],
      ['en cajita', ''],
      ['aji morron', 'morron'],
      ['ajo  (', 'ajo'],
      ['deshidratado', ''],
      ['ajos', 'ajo'],
      [' en polvo', ''],
      ['pasados', ''],
      ['tupper', ''],
      ['verduras para sopa', ''],
      ['verdes', 'verde'],
      ['salsa tomate', 'salsa de tomate'],
      ['pure de tomate', 'salsa de tomate'],
      ['tomate pisado', 'salsa de tomate'],
      ['pizca de', ''],
      [' de  min', ''],
      [' de  kg', ''],
      ['pollo pollo, mayonesa', 'pollo'],
      ['trozado', ''],
      [', use g de pechuga y  de muslo', ''],
      ['polvo para hornear', 'polvo de hornear'],
      ['salsa criolla lista', 'salsa criolla'],
      ['s de ajo', 'ajo'],
      ['rs manteca', 'manteca'],
      ['rollitos', ''],
      [' para cocinar', ''],
      ['ralladura de medio limon', 'ralladura de limon'],
      ['ralladura de  limon', 'ralladura de limon'],
      ['r lechuga', 'lechuga'],
      [' en barra', ''],
      ['feteado', ''],
      ['de maquina', ''],
      ['  extra fino', ''],
      ['*', ''],
      [' tipo casamcrem', ''],
      ['seco', ''],
      ['puerros', 'puerro'],
      ['puerro gr', 'puerro'],
      ['quesos', 'queso'],
      ['quedo', 'queso'],
      ['porotos', 'poroto'],
      ['blancos', 'blanco'],
      ['negros', 'negro'],
      ['pallares', 'pallar'],
      ['porciones', ''],
      ['rojos', 'rojo'],
      ['pimientos', 'pimiento'],
      ['pimiento', 'morron'],
      ['juliana', ''],
      ['arabes', 'arabe'],
      ['pequena de sal', 'sal'],
      ['pedacitos de ', ''],
      ['pechugas de pollo hervidas', 'pechuga de pollo'],
      ['. puede ser cualquier tipo de corte para milanesas de carne', ''],
      ['pechito se cerdo', 'pechito de cerdo'],
      [' en vez de patitas de cerdo', ''],
      ['patitas', 'patita'],
      ['patitas de cerdo', 'pata de cerdo'],
      ['patas', 'pata'],
      ['chancho', 'cerdo'],
      ['parrilla', ''],
      ['para los ', ''],
      ['para las ', ''],
      ['para la ', ''],
      ['para el ', ''],
      ['paq de ', ''],
      ['papa s', ''],
      ['papa rusticas en  essen', 'papa'],
      ['mediana', ''],
      ['en cubitos. tambien puede ser batata,', ''],
      ['fritas', 'frita'],
      ['saladas', ''],
      ['salada', ''],
      ['salados', ''],
      ['salado', ''],
      [' cortada en cubos', ''],
      ['panceta de cerdo', ''],
      ['panceta ahumada  g', ''],
      [' calentado en la', ''],
      ['madura', ''],
      ['maduro', ''],
      ['otros necesario', ''],
      ['ozobuco', 'osobuco'],
      ['opcionales', ''],
      ['opcional', ''],
      ['ollas', ''],
      ['olla alta', ''],
      ['nueces', 'nuez'],
      ['o  de condimento para rellenos y empanada', ''],
      ['o  huevo fritos', ''],
      ['o cantidad necesaria de agua', ''],
      ['o la especia que desees!', ''],
      ['naranjas', 'naranja'],
      ['muzzarella', 'mozzarella'],
      ['morrones', 'morron'],
      [' y medio rojo', ''],
      ['morron verde  rojo', 'morron verde'],
      ['  cuadrados de  por  cm', ''],
      ['morron rojo,', 'morron rojo'],
      [' y verde', ''],
      ['morron amarillo y', 'morron amarillo'],
      ['morcillas', 'morcilla'],
      ['moras', 'mora'],
      ['cocido, limpio tiras finitas de  cm de largo por', ''],
      ['finas tiras', ''],
      ['mollejitas de corazon', 'molleja'],
      ['mollejas', 'molleja'],
      ['ml agua', 'agua'],
      ['ml crema de leche', 'crema de leche'],
      ['ml leche', 'leche'],
      ['molde desmontable  cm', ''],
      ['/salsa de moras', ''],
      ['filete', ''],
      ['mejillones con cascara', 'mejillon'],
      ['medialunas', 'medialuna'],
      ['masa de empanada', 'tapa de empanada'],
      ['masa de tacos', 'tortilla'],
      ['masa para empanada para horno comparda', 'tapa de empanada'],
      ['manzanas', 'manzana'],
      [' y cortadas en cubos', ''],
      ['pomada', ''],
      ['mantequilla', 'manteca'],
      ['/grasa vacuna', ''],
      ['derretida', ''],
      ['(  gr de manteca en total', ''],
      ['blanda', ''],
      [' para locro', ''],
      ['lta. choclo en grano', 'choclo'],
      ['lomo de novillo', ''],
      ['organicos', ''],
      ['organico', ''],
      ['limones', 'limon'],
      ['levadura en pan chiquita', 'levadura'],
      ['lenteja en bolsa', 'lenteja'],
      ['+', ''],
      ['descremada', ''],
      ['light', ''],
      ['lo necesario', ''],
      ['yo use es la que tenia', ''],
      ['lata de', ''],
      ['lata', ''],
      ['granos de', ''],
      ['sin piel', ''],
      ['amarillos', 'amarillo'],
      ['langostinoss para decorar', 'langostino'],
      ['lamina de papel de aluminio del tamano del molde', ''],
      ['la piel amarilla de un limon', 'ralladura de limon'],
      ['kg de carne para asado', 'carne'],
      ['dicha', ''],
      ['jugo de  limones', 'jugo de limon'],
      ['/fiambre', ''],
      ['principales', ''],
      ['a temperatura ambiente', ''],
      ['batido con leche', ''],
      ['duros', 'duro'],
      ['cortditos', ''],
      ['huevo duros s', 'huevo duro'],
      ['huevo hervidos', 'huevo duro'],
      ['para agregar al final de la carbonada', ''],
      ['para pintar', ''],
      ['y  yema. yo utilizo los que con cascara pesan  gramos', ''],
      ['y una clara', ''],
      ['otro secreto', ''],
      ['ideas relleno', ''],
      ['huevas frescas de corvina', 'huevo de corvina'],
      ['huesitos', 'hueso'],
      ['leudantes', 'leudante'],
      [', una cda', ''],
      ['harina de', 'harina'],
      ['-', ''],
      ['almendras', 'almendra'],
      ['   gr', ''],
      ['cda colmada', ''],
      ['  grs', ''],
      ['  mas  gramos de polvo de hornear', ''],
      ['  todo uso', ''],
      ['huevo duro s', 'huevo duro'],
      ['cucharada polvo de hornear', ''],
      ['guarnicion', ''],
      [' para feir', ''],
      ['animal', ''],
      ['de pella', 'vacuna'],
      ['patrios', ''],
      ['garbanzos', 'garbanzo'],
      ['harina paraguay', 'harina maiz'],
      ['queso cascara roja  grueso', 'queso'],
      ['queso cascara roja', 'queso'],
      ['gr.de harina maiz paraguaya', 'harina maiz'],
      ['gracias chincu sancochado previo al laurel', ''],
      ['galletitas', 'galletita'],
      ['galletita chocolinas', 'chocolinas'],
      ['harina maiz precocida, coccion rapida, para polenta', 'harina maiz'],
      ['harina trigo tamizada', 'harina'],
      ['blanco cremoso untable', 'blanco'],
      [' tipo cuartirolo', 'cuartirolo'],
      ['frutillas', 'frutilla'],
      ['congeladas', ''],
      ['congelada', ''],
      ['congelados', ''],
      ['congelado', ''],
      ['frutas', 'fruta'],
      ['para decorar', ''],
      ['fritura  aceite', ''],
      ['puse tirabuzon de vegetales', ''],
      ['yo elegi coditos', ''],
      ['figasa', 'figaza'],
      ['figasitas', 'figaza'],
      ['de manteca', ''],
      ['por persona', ''],
      ['fecula de maicena', 'fecula de maiz'],
      ['maicena', 'fecula de maiz'],
      ['ajo porro', 'puerro'],
      [' la cantidad depende si te gusta mas', ''],
      [' medio podillo', ''],
      [' un pocillo', ''],
      ['ahi molido', 'aji molido'],
      ['  mi secreto', ''],
      [' fresca', ''],
      ['grados', ''],
      ['almejas .', 'almejas'],
      ['alinos', ''],
      ['  g azucar   cc agua', ''],
      ['almidon', 'fecula'],
      ['anco batata', 'zapallo anco'],
      ['hervido', ''],
      ['arroz largo y fino', 'arroz largo fino'],
      ['arvejas', 'arveja'],
      ['atadito', ''],
      ['atado ', ''],
      ['atun atun, lechuga, mayonesa', 'atun'],
      ['azucar blanca', 'azucar'],
      ['azucar fermento', 'azucar'],
      [' para espolvorear', ''],
      ['implapable', 'impalpable'],
      ['y gotas de jugo de limon glase', ''],
      ['en el relleno', ''],
      ['adas tostadas', ''],
      ['repeladas', ''],
      ['bananas congeladas', 'banana'],
      ['bananas', 'banana'],
      ['barata', ''],
      ['chica', ''],
      ['batatas', 'batata'],
      ['batata s', 'batata'],
      ['bife por persona', ''],
      ['bifes de', ''],
      ['bife de', ''],
      ['bola lomo', 'bola de lomo'],
      ['bolas de arroz', 'bola de arroz'],
      ['bollos', 'masa'],
      ['masa de pan', 'masa'],
      ['boniatos', 'boniato'],
      ['brochetas', 'brocheta'],
      ['brotes', 'brote'],
      ['cabecita', ''],
      ['c/ sal', ''],
      ['cabeza de ', ''],
      ['caldito', 'caldo'],
      ['calabaza anco cita', 'zapallo anco'],
      ['calamaress', 'calamar'],
      ['caldo para carne', 'caldo de carne'],
      ['cant necesaria', ''],
      [', cantidad necesaria.  cucharadas aceite de oliva preferentemente', ''],
      ['camarones', 'camaron'],
      ['capsula azafran', 'azafran'],
      ['canela en rama', 'canela'],
      [' de vaca  ya sin grasa', ''],
      ['carne costillar de  kilitos', 'costillar'],
      ['molida', 'picada'],
      [' si prefieren', ''],
      ['especial', ''],
      [', puede ser paleta', ''],
      [', yo use asado ruso', ''],
      ['carnes cocidas', 'carne'],
      ['casancrem', 'queso crema'],
      ['abrillantadas', 'abrillantada'],
      ['  cortada en', ''],
      ['cebolla blanca', 'cebolla'],
      [' bien picada', ''],
      [' caramelizadas con panceta ahumada/bacon', ' caramelizada'],
      ['chica', ''],
      [' bien picadita', ''],
      [' cucharadas aceite de oliva', ''],
      ['no muy s', ''],
      [' para servir', ''],
      ['picada fina', ''],
      ['picada gruesas', ''],
      ['lentejas', 'lenteja'],
      ['  ', ' '],
      ['receta para molde de centimetros', ''],
      ['osobuco y/o rosbeaf', 'osobuco'],
      ['mermelada/salsa de mora', 'mermelada'],
      ['limpio', ''],
      ['licuadora', ''],
      ['haria', 'harina'],
      ['parrillera', ''],
      ['tacos', 'taco'],
      [' con cascara', ''],
      ['batidora electrica', ''],
      [' cortada en', ''],
      ['champinoness', 'champinon'],
      ['champinones', 'champinon'],
      ['picadas gruesas', ''],
      ['picadita', ''],
      ['cebolla s', 'cebolla'],
      ['. si las prefieren mas jugosas agregar mas cebolla', ''],
      ['cebollita', 'cebolla'],
      ['cerezas', 'cereza'],
      ['confitadas', 'confitada'],
      [' en pomo', ''],
      ['chauchas', 'chaucha'],
      ['chinchulines', 'chinchulin'],
      [' precocido escurrido', ''],
      ['rodajas', ''],
      ['choclos', 'choclo'],
      [' s cortados al medio', ''],
      [' y una negra', ''],
      [' de gr', ''],
      ['para derretir', ''],
      ['chocolina de gr', 'chocolinas'],
      ['chocolinas de', 'chocolinas'],
      [' pequenos trozos y previamente', ''],
      ['chocloss', 'choclo'],
      ['cholos', 'choclo'],
      ['pequenos trozos y previamente', ''],
      ['chorizos', 'chorizo'],
      ['colorados', 'colorado'],
      ['criollos', 'criollo'],
      ['parrilleros', ''],
      ['puro cerdo', ''],
      ['chorrito de', ''],
      ['churrasquitos de', ''],
      [' en rama', ''],
      ['ciruelas pasas', 'ciruela en pasa'],
      ['clasico', ''],
      ['  pesar las clara!!!!', ''],
      ['condimento mezcla', ''],
      ['colorante celeste', ''],
      ['colorante comestible del color que prefieran', ''],
      ['colorantes', ''],
      ['colorante', ''],
      ['condimentos', ''],
      ['condimento', ''],
      ['colador', ''],
      ['colmadas de', ''],
      [' de asado', ''],
      [ 'de vaca', ''],
      ['batida', ''],
      ['crema de leche', 'crema'],
      ['para batir', ''],
      ['crema helada de mora', 'helado de mora'],
      [' cortada en bifes', ''],
      ['cubierta crema de leche batida', 'crema,'],
      ['cuchadadas de ', ''],
      ['cucharadita de ', ''],
      ['cuerito', 'cuero'],
      ['  check our recipe to make home made dulce de leche', ''],
      ['dulce leche', 'dulce de leche'],
      ['dulces dulce de leche', 'dulce de leche'],
      [' cdita de te', ''],
      ['especias', ''],
      ['especias de reposteria', ''],
      ['especias surtidas', ''],
      [' y ', ', '],
      ['/', ','],
      ['.', ','],
      ['  a gr', ''],
      ['bifes churrasco de ', ''],
      ['verduras', 'verdura'],
      ['cant,nec', ''],
      ['en este use  surtida', ''],
      ['un poquito ', ''],
      ['un caldo knorr de', 'caldo'],
      ['unas hojitas de', ''],
      ['varias', ''],
      ['varios', ''],
      ['!', ''],
      [' con ', ''],
      ['rosca de morci', 'morcilla'],
      ['rama de ', ''],
      ['pimenton,', ''],
      ['deshuesado', ''],
      [' cantidad necesaria', ''],
      ['centimetros cubicos de', ''],
      ['cucharada ', ''],
      [' para pincelar', ''],
      ['ralladura de piel de limon', 'ralladura de limon'],
      ['ajo s', 'ajo'],
      ['al gusto', ''],
      ['bifecitos de ', ''],
      ['botella de ', ''],
      ['botella', ''],
      ['calabacines s', 'calabacin'],
      ['calabacines', 'calabacin'],
      ['para rebozar', ''],
      ['casero', ''],
      ['vegetales', 'verdura'],
      ['natural', ''],
      ['en cubitos', ''],
      ['tomate perita s', 'tomate perita'],
      ['tazon de', ''],
      ['tazas de ', ''],
      ['copos de avena', 'copo de avena'],
      ['picada en cuadritos', ''],
      ['helada', ''],
      ['tazas', ''],
      ['taza', ''],
      ['tarro de ', ''],
      ['yemas de huevo', 'yema'],
      ['yema de huevo', 'yema'],
      ['soperas de ', ''],
      ['tallos de', ''],
      ['soperasasa vacuna', 'soperasasa'],
      ['yogures griegos', 'yogur griego'],
      ['trozo de ', ''],
      ['trozo', ''],
      ['untable', ''],
      ['pipas de girasol', 'semilla de girasol'],
      ['guisantes', 'poroto'],
      ['guisante', 'poroto'],
      ['azucar almibar', 'azucar'],
      ['soperas de', ''],
      ['sin sal', ''],
      ['soperas aceite', 'aceite'],
      ['soperas aceite de girasol', 'aceite de girasol'],
      ['soperas aceite de oliva', 'aceite de oliva'],
      ['saltear', ''],
      ['sal,', ''],
      ['rodaja de ', ''],
      ['rellenos ', ''],
      ['rebanadas de', ''],
      ['reblandecida', ''],
      ['ramas de ', ''],
      ['descremado', ''],
      ['descremada', ''],
      ['untable', ''],
      ['para untar', ''],
      ['queso ,', 'queso'],
      ['punado de', ''],
      [' las papa', ''],
      ['uvas', 'uva'],
      ['postre de ', ''],
      ['povlo', 'polvo'],
      ['pure de', ''],
      ['postre', ''],
      ['polvos', 'polvo'],
      ['hornear,', 'hornear'],
      ['pollos', 'pollo'],
      ['pizca', ''],
      ['pimineta', 'pimienta'],
      ['pequeno de ', ''],
      ['pimineto', 'morron'],
      ['pimenoon', 'pimenton'],
      ['pellizcos de ', ''],
      ['pechugas', 'pechuga'],
      ['deshuesada', ''],
      ['cocidas cortadas', ''],
      ['patatas', 'papa'],
      ['patata', 'papa'],
      ['pastilla de ', ''],
      ['pasta seca', 'fideos'],
      [' sin carozo', ''],
      ['pasas', 'pasa'],
      ['paquete de ', ''],
      ['masa para empanada', 'tapa de empanada'],
      ['paquetes de ', ''],
      [' peladas enteras', ''],
      ['picadas', ''],
      ['picada', ''],
      ['del dia anterior', ''],
      ['de campo', ''],
      ['otas de ', ''],
      ['obre de ', ''],
      ['o  de ajo', 'ajo'],
      ['o huevo duro', 'huevo duro'],
      ['nata para montar% de materia grasa', 'crema'],
      ['nata', 'crema'],
      ['pequeno', ''],
      ['cubos', ''],
      [' remojada en leche', ''],
      ['despinada', ''],
      [' casera sin azucar', ''],
      ['troceados', ''],
      ['menudos', 'menudo'],
      ['mazorca de maiz,', 'choclo'],
      ['mazorca', 'choclo'],
      ['manojos de ', ''],
      ['manojo de ', ''],
      ['masa de harina para empanada', 'tapa de empanada'],
      ['litros de ', ''],
      ['para exprimir', ''],
      ['limon exprimido', 'jugo de limon'],
      ['libra de ', ''],
      ['de panaderia', ''],
      ['de panadero', ''],
      ['desamargada', ''],
      ['lechera', ''],
      ['leche liquida', 'leche'],
      ['laminas de', ''],
      ['lamina de', ''],
      ['kilos de ', ''],
      ['kilogramos de ', ''],
      ['kilogramo de ', ''],
      ['kilo de ', ''],
      ['casera', ''],
      ['huevo,', 'huevo'],
      [' en trocitos', ''],
      ['batido', ''],
      ['hoja de', ''],
      ['hierbas provenzales', 'provenzal'],
      ['harina trigo )', 'harina trigo'],
      [' todo uso', ''],
      ['preparada', ''],
      ['fina de', ''],
      [' en escamas', ''],
      ['galletita', 'gelatina'],
      ['galletas dulces sin relleno', 'galleta dulce'],
      ['fruta secas,confitada variadas', 'fruta seca'],
      ['flauta de pan suave', 'pan flauta'],
      ['fetas de ', ''],
      ['hervida', ''],
      ['espinacas', 'espinaca'],
      ['escurrida', ''],
      ['en punto', ''],
      [' apto coccion', ''],
      ['dulce membrillo', 'dulce de membrillo'],
      ['y,o dulce de membrillo', ''],
      ['libre de gluten', ''],
      ['para rellenar', ''],
      ['discos de tapa', 'tapa de'],
      ['discos de', 'tapa de'],
      ['discos para', 'tapa de'],
      ['desmenuzado', ''],
      ['de agua', 'agua'],
      ['de ajo', 'ajo'],
      ['de avena', 'avena'],
      ['de esencia de vainilla', 'esencia de vainilla'],
      ['de fecula de mandioca,', 'fecula de mandioca'],
      ['de leche', 'leche'],
      ['de leche,', 'leche'],
      ['de mos', 'mostaza'],
      ['de polvo de hornear', 'polvo de hornear'],
      ['de polvo de hornear sin gluten', 'polvo de hornear'],
      ['de queso', 'queso'],
      ['de queso muzarella', 'queso mozzarella'],
      ['de queso tipo fontina', 'queso fontina'],
      ['de ralladura de limon', 'ralladura de limon'],
      ['de sal', 'sal'],
      ['de ternera s de la parte de la nalga cortadoscmosor', 'nalga'],
      ['cucharadas soperas', ''],
      ['cucharaditas de ', ''],
      ['cubo de ', ''],
      ['copa de', ''],
      ['cominos', 'comino'],
      ['colmada de ', ''],
      ['contorno', ''],
      ['chorro de', ''],
      ['ciruelas', 'ciruela'],
      ['chorizos', 'chorizo'],
      ['artesanales argentinos', ''],
      ['semi amargo', 'semiamargo'],
      ['desgranados', 'desgranado'],
      ['sus hojas', ''],
      ['argentino', ''],
      ['laminados', ''],
      ['champinon ados', 'champinon'],
      ['champignnones', 'champinon'],
      ['champignones', 'champinon'],
      ['champignon', 'champignon'],
      ['centimetros cubicos ', ''],
      ['cebolllas','cebolla'],
      ['cebolletasus hojas', 'cebolleta'],
      ['finamente', ''],
      ['cortadas en rebanadas', ''],
      ['cortadas en cuartos', ''],
      ['cortadas en', ''],
      ['caldo de verdura', 'caldo vegetal'],
      ['zumo de', 'jugo de'],
      ['pequena', ''],
      ['yogurt', 'yogur'],
      ['yoghurt', 'yogur'],
      ['yemas', 'yema'],
      ['vino tinto malbec', 'vino malbec'],
      ['vinagretamos', 'vinagreta'],
      [' a la', ''],
      [' al vapor', ''],
      ['asadas', ''],
      ['cocidas', ''],
      ['al horno', ''],
      ['horneados', ''],
      ['vaso agua', 'agua'],
      ['vainilla en pasta', 'vainilla'],
      ['upremas', 'supremas'],
      ['uprema', 'suprema'],
      ['aplastadas para milanesa', ''],
      ['unas ramitas de', ''],
      ['una ', ''],
      ['triturados', 'triturado'],
      ['tomate triturado', 'salsa de tomate'],
      ['confitados', 'confitado'],
      ['tomate en', 'tomate'],
      ['tomate endo', 'tomate'],
      ['hidratados', 'hidratado'],
      ['tomates', 'tomate'],
      ['tomatedo', 'tomate'],
      ['tomate ,', 'tomate'],
      ['tiernos', ''],
      ['tiras', ''],
      ['delgadas', ''],
      ['finas', ''],
      ['rayado', ''],
      ['te de pimenton', 'pimenton'],
      ['tallo de', ''],
      ['tapa de empanada des', 'tapa de empanada'],
      ['para horno', ''],
      ['sirope de ', 'salsa de'],
      ['suficiente', ''],
      ['para barnizar', ''],
      ['para cubrir los s de pescado', ''],
      ['para empanizar', ''],
      ['semillas', 'semilla'],
      ['sin cascaras ni semillas', ''],
      ['sin hueso', ''],
      ['sin las nervaduras', ''],
      ['sin leudante', ''],
      ['sin semillas', ''],
      ['sin semillas hidratadas', ''],
      ['espesa', ''],
      ['salsa bechamel', 'salsa blanca'],
      [' a tu gusto', ''],
      ['salchicha calabresa,', 'salchicha calabresa'],
      ['entrefina', ''],
      ['sal extra', 'sal'],
      ['sala criolla', 'salsa criolla'],
      ['cubitos', ''],
      ['salas criolla', 'salsa criolla'],
      ['s de atun en aceite', 'atun'],
      ['ricotta', 'ricota'],
      ['ramito de', ''],
      ['ramita de', ''],
      ['ramo de ', ''],
      ['ranos de ', ''],
      ['rebanadas gruesas', ''],
      ['remojados desde la noche anterior', ''],
      ['de la cascara ', ''],
      ['queso tipo mar del p', 'queso mar del plata'],
      ['en grumos', ''],
      ['semicurado', 'semiduro'],
      ['relleno', ''],
      ['para gratinar', ''],
      ['queso mozzarella en', 'queso mozzarella'],
      [' en fetas', ''],
      ['queso duro tipo pate gras', 'queso pategras'],
      ['puede ser', ''],
      ['puedes usar ', ''],
      ['preferiblemente de ', ''],
      ['preferiblemente', ''],
      ['potes de ', ''],
      ['presas', ''],
      ['placas de ', ''],
      ['recien', ''],
      ['en granos', ''],
      ['en grano', ''],
      ['piezas', ''],
      ['picana de', 'picana'],
      ['pernil de cerdohueso', 'pernil de cerdo'],
      ['peras s', 'pera'],
      ['peras', 'pera'],
      ['peladas', ''],
      ['pelada', ''],
      ['pechuga de pollo,', 'pechuga de pollo'],
      ['pata muslos de pollo', 'pata muslo'],
      ['pata muslo de pollo', 'pata muslo'],
      ['paquete', ''],
      ['para acompanar', ''],
      ['para aderezar', ''],
      ['para barnizar las empanada', ''],
      ['para empanar', ''],
      ['para empanizar', ''],
      ['para engrasar', ''],
      ['para engrasar el molde', ''],
      ['para engrasar los moldes', ''],
      ['para espesar la salsa', ''],
      ['para esto haremos lista aparte', ''],
      ['para horno', ''],
      ['para pizza', ''],
      ['para rociar', ''],
      ['para sazonar', ''],
      ['panes', 'pan'],
      ['pan para', 'pan de'],
      ['sandwichs', 'sandwich'],
      ['horneadas', ''],
      ['paltas', 'palta'],
      ['palito de', ''],
      ['otros', ''],
      ['bistec', 'bife'],
      ['caramelizadas', 'caramelizada'],
      ['muy suave', ''],
      ['necesaria', ''],
      ['necesario', ''],
      ['nabos', 'nabo'],
      [' u otro queso fundente', ''],
      ['lomos', 'lomo'],
      ['amos', ''],
      ['mos ', 'mostaza '],
      ['morron verde,', 'morron verde'],
      ['morron s de conserva', 'morron en conserva'],
      ['asados,', ''],
      ['asados', ''],
      ['asado,', ''],
      ['asado', ''],
      ['morron morron', 'morron'],
      ['cortados en', ''],
      ['de conserva', 'en conserva'],
      ['morron rojo en', 'morron rojo'],
      ['morron rojo verde', 'morron rojo'],
      ['cortados en', ''],
      ['morron verde en', 'morron verde'],
      ['morcilla atada', 'morcilla'],
      ['mileche', 'leche'],
      ['milanesas', 'milanesa'],
      ['mejillonessu valva', 'mejillon'],
      ['mejillones', 'mejillon'],
      ['medida de ', ''],
      ['mazo de', ''],
      ['mayonesa y,o queso crema', 'mayonesa'],
      ['matambre de cerdo de', 'matambre de cerdo'],
      ['mas de fecula de maiz', 'fecula de maiz'],
      ['mariscos variados', 'mariscos'],
      ['margarina de hojaldre', 'margarina'],
      ['mandarinas s', 'mandarina'],
      ['mandarinas', 'mandarina'],
      ['sin cascara', ''],
      ['manichocolate', 'mani'],
      ['manteca  la', 'manteca'],
      ['los moldes', ''],
      ['lonjas de', ''],
      ['en lonjas', ''],
      ['lonjas', ''],
      ['litro de ', ''],
      ['litro ', ''],
      ['sin semilla', ''],
      ['liposoluble', ''],
      [' en mitades', ''],
      ['enteras', ''],
      [' de a kilos', ''],
      ['kilos', ''],
      ['kilo', ''],
      ['laminas para canelones', ''],
      ['laminas', ''],
      ['langostinos', 'langostino'],
      ['langostino s ys', 'langostino'],
      ['langostinos,s', 'langostino'],
      ['langostinoss', 'langostino'],
      ['las empanada', ''],
      ['jugo de un', 'jugo de'],
      ['jugo de una', 'jugo de'],
      ['en tiritas', ''],
      ['en lonchas', ''],
      ['jamon cocido en', 'jamon cocido'],
      ['huevo cocido', 'huevo duro'],
      ['huevo duro,', 'huevo duro'],
      ['fritos', 'frito'],
      ['ligeramente', ''],
      ['por porcion', ''],
      ['revueltos', 'revuelto'],
      ['huevo salsa', 'huevo'],
      ['separando yema', ''],
      ['hidratadas', ''],
      ['mas cucharada', ''],
      ['harina para', 'harina'],
      ['harina reposteria', 'harina'],
      ['grasa de vacuna', 'grasa vacuna'],
      ['gruesas queso provolone', 'queso provolone'],
      ['grajeas', 'grageas'],
      ['gotitas de ', ''],
      ['gajo de ', ''],
      ['frutos rojo', 'frutos rojos'],
      ['frutillas', 'frutilla'],
      ['fresass', 'frutilla'],
      ['fresas', 'frutilla'],
      ['fresa', 'frutilla'],
      ['largos', ''],
      ['finos', ''],
      ['cruda', ''],
      ['limpias', ''],
      ['espinacas', 'espinaca'],
      ['escalopes de lomo fino', 'escalope de lomo'],
      ['en de hojas verde', 'hojas verdes'],
      ['en de lechuga', 'lechuga'],
      ['en de tomate', 'tomate'],
      ['en de tomatehojas verde', 'tomate'],
      ['en de tu preferencia', ''],
      ['en ocasiones las recetas llevan algun tipo de plato complementario,', ''],
      ['embutidos', 'embutido'],
      ['el molde', ''],
      ['el pan', 'pan'],
      ['duro pero fina', ''],
      ['disuelta en el ', ''],
      ['disco de', ''],
      ['descorazonadas', ''],
      ['desmenuzada', ''],
      ['desvenadas', ''],
      ['diente ajo', 'ajo'],
      ['cuchara de ', ''],
      ['cucharita ', ''],
      ['cucharada', ''],
      ['cucharadita ', ''],
      ['cubito de ', ''],
      ['cuartos de limon quemado', 'limon'],
      ['cuartos', ''],
      ['liquida', ''],
      ['crema muy', 'crema'],
      ['cremas', 'crema'],
      ['costillar de ternera de', 'costillar de ternera'],
      ['copas de', ''],
      ['cortadas al bies', ''],
      ['cortadas por la mitad', ''],
      ['cortadas', ''],
      ['cortados por la mitad', ''],
      ['cortado', ''],
      ['costados en', ''],
      ['molido', ''],
      ['cogollo de lechuga unas hojas', 'lechuga'],
      ['cocido y', ''],
      ['cocida', ''],
      ['churrascos de ', ''],
      ['chuletas de', ''],
      ['chorro de', ''],
      ['chorro', ''],
      ['chuletas', ''],
      [',hueso ya', ''],
      ['mixtos', ''],
      ['chorizo s', 'chorizo'],
      ['chorizoamostaza cada uno', 'chorizo'],
      ['chocolate para', 'chocolate'],
      ['chinchulins', 'chinchulin'],
      ['chinchulines', 'chinchulin'],
      ['cebolla,', ''],
      ['cebolla mente', 'cebolla'],
      ['cebolla en', 'cebolla'],
      ['carres de cerdohueso', 'carre de cerdo'],
      ['carnes', 'carne'],
      ['cantidad  de', ''],
      ['cantidad', ''],
      ['cajas de', ''],
      ['cajas', ''],
      ['caja de', ''],
      ['caja', ''],
      ['cabezaajo', 'ajo'],
      ['bulbo de ', ''],
      ['brocolis', 'brocoli'],
      ['bondiola de cerdo,', 'bondiola de cerdo'],
      ['bolsa de', ''],
      ['bolsa', ''],
      ['bola de helado', 'helado'],
      ['blando', ''],
      ['sodico', ''],
      ['de sodio', ''],
      ['bifes s en', ''],
      ['bifes s superiores', ''],
      ['barra de', ''],
      ['berenjenas', 'berenjena'],
      ['morena', 'moreno'],
      [' en hojuelas pre', ''],
      [' en en aceite escurrido', ''],
      ['en aceite', ''],
      ['atados de ', ''],
      ['arveja al', 'arveja'],
      ['algunas hojas', ''],
      ['arandanos', 'arandano'],
      ['anana en', 'anana'],
      ['anchoas', 'anchoa'],
      ['tostadas', ''],
      ['laminadas', ''],
      ['almendra adas', 'almendra'],
      ['alletas ', ''],
      ['etilico', ''],
      ['ajo,', ''],
      ['triturado', ''],
      ['en ruedas', ''],
      ['ajies', 'aji'],
      ['rojo,', ''],
      ['picantes,', ''],
      ['picantes', ''],
      ['picante,', ''],
      ['picante', ''],
      ['aguacates', 'palta'],
      ['aguacate', 'palta'],
      ['hirviendo', ''],
      ['agua mas', 'agua'],
      ['mineral ligera', ''],
      ['mineral', ''],
      ['acelgas', 'acelga'],
      ['verde,', ''],
      ['negras', 'negra'],
      ['aceite de oliva extra virgen', 'aceite de oliva'],
      ['aceite de oliva para', 'aceite de oliva'],
      ['aceite de oliva virgen extra', 'aceite de oliva'],
      ['aceite extra', 'aceite'],
      ['aceite virgen de oliva', 'aceite de oliva'],
      ['aceite oliva extra virgen', 'aceite de oliva'],
  ]